version: '3.2'
services:
  db:
    image: postgres
    container_name: "bitmonger_db"
    volumes:
      - development_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  app:
    container_name: "bitmonger_app"
    environment:
      DATABASE_USER: "${POSTGRES_USER}"
      DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/home/bitmonger
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  development_db:
